### ISSUE TITLE
RNA velocity

### ISSUE THREAD

**Issue by suminwei2772** [theislab/paga#19]
Hi,
I wanted to incorporate RNA velocity into PAGA. I see that the example posted in Issue #11 has been removed. Would you be able to post the example again to show how to obtain spliced/unspliced counts using RNA velocity and incorporate into PAGA?
Thank you,
Lisa

**Comment by VolkerBergen** [comment]
@suminwei2772 An example of applying directed PAGA can be found at https://scvelo.readthedocs.io/VelocityBasics.html.

**Comment by andynkili** [comment]
@VolkerBergen ,

Could you please refresh the link? The one you are referencing is dead.

Best,
Andy
