### ISSUE TITLE
Genome Biology link is wrong?

### ISSUE THREAD

**Issue by zaczap** [theislab/paga#7]
The first line of the README links to [here](https://doi.org/10.1186/s13059-019-1663-x) but I think you want it to link [here](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1663-x)? Or at least correct the DOI link.

**Comment by falexwolf** [comment]
Sorry, the DOI seems still broken, it's the correct DOI...

**Comment by falexwolf** [comment]
Replaced the doi with the url until it starts working again.
