### ISSUE TITLE
Dahlin data access

### ISSUE THREAD

**Issue by sgmccalla** [theislab/paga#8]
I am not able to access the Dahlin 2018 data:
https://gottgens-lab.stemcells.cam.ac.uk/adultHSPC10X/

**Comment by falexwolf** [comment]
Strange, there is a link there, right? https://gottgens-lab.stemcells.cam.ac.uk/adultHSPC10X/html_links/Notebook_input_data.tar.gz

Also a link to the preprocessing notebook.

If you want processed data, get back to me.

**Comment by sgmccalla** [comment]
Thanks!

**Comment by scontcast** [comment]
Hi @falexwolf , I would like to use Dahlin 2018 data as a reference to map my cells. 
Would it be possible to obtain the processed data? 

Thanks!
