### ISSUE TITLE
paga on integrated datasets

### ISSUE THREAD

**Issue by DHGK** [theislab/paga#9]
Hi paga community,

Previously I have integrated two of my datasets using Seurat CCA-based method. I'm now hoping to infer the trajectory using paga. However, since I have processed data using seurat, I'm not sure which matrix should I use from seurat object to do the paga -- should I use raw data count matrix or combined &normalized matrix? Or if I'm only supposed to run paga on single dataset instead of on a seurat-combined datasets.

Thanks!

**Comment by falexwolf** [comment]
Hey! PAGA can be run on the combined & normalized (integrated) matrix. The same matrix as the one that Seurat runs the joint clustering on. Looking for shared trajectories is, technically, analogous to looking for shared clusters. Both amounts to looking for shared connected regions in the cross-data  neighborhood graph.

**Comment by DHGK** [comment]
@falexwolf 

Thank you so much for your reply and the explanation is very helpful!

Best wishes
